#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBox;
                ref class ComboBox;
                ref class ScrollViewer;
                ref class StackPanel;
                ref class AppBarButton;
                ref class HyperlinkButton;
            }
        }
    }
}

namespace Triggy
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::TextBox^ tbTriggername;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ cbType;
        private: ::Windows::UI::Xaml::Controls::ScrollViewer^ svComponents;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ spComponents;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ abbNewProject;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ abbSaveAs;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ abbLoad;
        private: ::Windows::UI::Xaml::Controls::AppBarButton^ abbExport;
        private: ::Windows::UI::Xaml::Controls::HyperlinkButton^ hlbProjectname;
    };
}

